export const PRICING_PLANS = [
  {
    id: 'starter',
    name: 'Starter',
    badge: null,
    isPopular: false,
    subtitle: 'Pilot a single agent.',
    monthlyPrice: 31,
    yearlyPrice: 25, // ~20% discount
    includedMins: '250 min',
    effectiveRate: '$0.13/min',
    agentsCount: '2 AI agents',
    ctaText: 'Get started',
    ctaTheme: 'ghost',
    features: [
      '2 AI voice agents',
      '250 included minutes',
      '$0.13/min effective rate',
      'Inbound & outbound calling',
      'Per-second billing',
      'Standard voice engine',
      'Call recording & audio logs',
      'Real-time transcription',
      'Email support',
    ],
  },
  {
    id: 'growth',
    name: 'Growth',
    badge: 'MOST POPULAR',
    isPopular: true,
    subtitle: 'Most teams start here.',
    monthlyPrice: 93,
    yearlyPrice: 74, // ~20% discount
    includedMins: '800 min',
    effectiveRate: '$0.12/min',
    agentsCount: '10 AI agents',
    ctaText: 'Choose Growth',
    ctaTheme: 'filled',
    features: [
      '10 AI voice agents',
      '800 included minutes',
      '$0.12/min effective rate',
      'Inbound & outbound calling',
      'Per-second billing',
      'Standard + premium voice stack',
      'Call recording & audio logs',
      'Real-time transcription',
      'Priority live support',
    ],
  },
  {
    id: 'scale',
    name: 'Scale',
    badge: 'ENTERPRISE SCALE',
    isPopular: false,
    subtitle: 'High-volume call centers.',
    monthlyPrice: 316,
    yearlyPrice: 252, // ~20% discount
    includedMins: '3,000 min',
    effectiveRate: '$0.11/min',
    agentsCount: 'Unlimited AI agents',
    ctaText: 'Get started',
    ctaTheme: 'ghost',
    features: [
      'Unlimited AI voice agents',
      '3,000 included minutes',
      '$0.11/min effective rate',
      'Inbound & outbound calling',
      'Per-second billing',
      'Realtime + ultra-low latency stack',
      'Call recording & audio logs',
      'Real-time transcription',
      'Dedicated success manager + SLA',
    ],
  },
];